The text test of add_integer
-------------------------------

Using ''say_my_name''

===============================

    >>> say_my_name = __import__('3-say_my_name').say_my_name

==============
Typical Test |
==============

    >>> say_my_name("Edouard", "NewGate")
    My name is Edouard NewGate

    >>> say_my_name("EPI", "phanie")
    My name is EPI phanie

    >>> say_my_name("1", "Douglas")
    My name is 1 Douglas

    >>> say_my_name("Antony", "3")
    My name is Antony 3


===============
   Error Type |
===============


    >>> say_my_name("Antony", 3)
    Traceback (most recent call last):
        ...
    TypeError: exceptions must derive from BaseException

    >>> say_my_name(4, "Nehemie")
    Traceback (most recent call last):
        ...
    TypeError: exceptions must derive from BaseException

    >>> print_square(-5.44)
    Traceback (most recent call last):
        ...
    TypeError: size must be an integer

    